# Generated by Django 4.2 on 2025-03-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.gamemode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.gamemode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.user')),
            ],
            options={
                'unique_together': {('user', 'game_mode')},
            },
        ),
    ]
